version: '2'
services:
  redis-cache:
    image: redis:latest
    ports:
      - 6379:6379

  my_project:
    image: my_project:1.0
    build:
      context: ./
    ports:
      - 8000:8000
    depends_on:
      - redis-cache