apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-project-app
spec:
  selector:
    matchLabels:
      app: my-project-app
  template:
    metadata:
      labels:
        app: my-project-app
    spec:
      containers:
      - name: my-project
        image: zdendaregistry.azurecr.io/my_project:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "258m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-project-app
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: my-project-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
spec:
  selector:
    matchLabels:
      app: my-project-app
  template:
    metadata:
      labels:
        app: my-project-app
    spec:
      containers:
      - name: redis-cache
        image: zdendaregistry.azurecr.io/redis:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache
spec:
  selector:
    app: my-project-app
  ports:
  - name: redis-cache
    port: 6379
    targetPort: 6379